### PR TITLE
 Run configurations in parallel

### PR DESCRIPTION
**Pull request by MarcusTomlinson**
This has shown to reduce cold run times by roughly 20%-30%:
chromium : ~0.720s -> ~0.580s
libreoffice : ~0.280s -> ~0.180s

### CODE REVIEW

**Comment by kenvandine** [comment]
@oSoMoN can you please take a look at this?

**Comment by oSoMoN** [comment]
I haven't measured the actual speedups by rebuilding snaps, I'll take your word on this.

The approach looks good to me.

One minor suggestion: how about making a function that runs a command and its parameters asynchronously (`exec_async()` maybe) and automatically adds the pid to `$PIDS`. This would ease maintenance, and avoid copy-pasta headaches (I can almost picture myself copy-pasting those two lines to exec a command asynchronously and forgetting to change the value associated to the pid in the array, and then scratching my head for hours when the launcher script reports that `make_user_fontconfig exited abnormally with status 42`).

**Comment by MarcusTomlinson** [comment]
> I haven't measured the actual speedups by rebuilding snaps, I'll take your word on this.
> 
> The approach looks good to me.
> 
> One minor suggestion: how about making a function that runs a command and its parameters asynchronously (`exec_async()` maybe) and automatically adds the pid to `$PIDS`. This would ease maintenance, and avoid copy-pasta headaches (I can almost picture myself copy-pasting those two lines to exec a command asynchronously and forgetting to change the value associated to the pid in the array, and then scratching my head for hours when the launcher script reports that `make_user_fontconfig exited abnormally with status 42`).

Good point, I'll do that

**Comment by oSoMoN** [comment]
LGTM, thanks!

**Pull request merged**
