### PR TITLE
snapcraft.yaml: include libraries for indicators support

### PR DESCRIPTION
**Pull request by 3v1n0**
This adds support to desktop indicators for snapped apps.

### CODE REVIEW

**Comment by 3v1n0** [comment]
These packages have now been SRUed to xenial, thus we can just use the `stage-packages` stanza

**Comment by 3v1n0** [comment]
Wondering if is the case to `export QT_QPA_PLATFORMTHEME=appmenu-qt5` if `$DISPLAY` is set and `$MIR_SOCKET` is not set...

Not sure how this will work in environments without appmenu support though... Mhmmh (maybe checking for `$XDG_CURRENT_DESKTOP` could be something to do too)

**Comment by didrocks** [comment]
Do you want more time to check that use case before we merge?

**Comment by 3v1n0** [comment]
Well, currently this is not really an issue, since in all the platforms where appmenu+indicators are used that var is already exported by the host's appmenu-qt5 package, but if that's removed there's no support...

So, it's just about how we want this to be handled: do we want to leave to the host system to support this or not, or we want to set that in the launcher anyway (without overriding, of course)?

**Comment by didrocks** [comment]
Well, let's add the support unconditionally I would say in the launcher and let the platform ignore it if there is no support on the other side, making sense? Tell me if/when you think we can merge this.

**Comment by 3v1n0** [comment]
Added the export stanza too

**Comment by didrocks** [comment]
Looking good to me!

**Pull request merged**
