### PR TITLE
Add pulseaudio to the LD_LIBARY_PATH of the platform snap

### PR DESCRIPTION
**Pull request by tjyrinki**
Qt Multimedia is failing due to not finding the library.

### CODE REVIEW

**Comment by didrocks** [comment]
see my comment on #24 and attached bug. I'm really not a fan and it seems Qt is doing something not right (or it should look for itself relative to each defined LD_LIBRARY_PATH), making sense?

**Comment by tjyrinki** [comment]
Ok. Renato could fill in with the details of what he sees when trying to run such an app. I'm wondering if it's not Qt itself but Pulseaudio that tries to find its private library from the usual location but cannot.

**Comment by didrocks** [comment]
That's more than possible that it's using RPATH or things like that. I'm not opposed to add it for those reasons, but will like that you dig into why it's needed actually

**Comment by tpeeters** [comment]
I ran into this also and reported issue #37 (before I saw this PR).

**Comment by didrocks** [comment]
Ok, no new one that one, pushed a fix to the common file thus. We can close this one.
Thanks everyone

**Comment by tjyrinki** [comment]
Thank you!

**Pull request closed without merging**
