### PR TITLE
Modify PATH so that xdg-open can be found

### PR DESCRIPTION
**Pull request by mardy**

### CODE REVIEW

**Comment by didrocks** [comment]
xdg-open was in PATH previously and the core snap regressed that. From the discussion on the ML, they committed to put usr/local/bin back in PATH, so I don't this is needed. Also it would create a diference in behavior between apps using desktop-launcher and other snaps. I don't think we want to introduce this kind of questioning. Thoughts?

**Comment by mardy** [comment]
Do we have a bug on the core snap about this?
I would propose to merge this (hopefully temporary) fix and then revert it later once the core snap is fixed.

**Comment by didrocks** [comment]
I don't have it off-hand, but maybe raise it again on the ML? (the more people complain, the more the snapd team might fix it).
I don't really like to put that workarounds, because we know they are going to live for a while, and create a discrepencies of behavior between snaps using the desktop helpers and those which don't.

Raise it first, if we see no action from them (there is as well the issue of the helper which aren't installed everywhere), let's revisit this, ok?

**Comment by ogra1** [comment]
xdg-open has been in /usr/local from day one in teh core snap, nothing regressed or changed in that part since it was initially added.

$ cat /snap/core/current/usr/local/bin/xdg-open 
#!/bin/sh
dbus-send --print-reply --session --dest=com.canonical.SafeLauncher / com.canonical.SafeLauncher.OpenURL string:"$1"

what is the exact issue you have here ? snap-confine forces /usr/local/bin into the path of every executed snap so the dbus call should work as well.

**Comment by didrocks** [comment]
xdg-open didn't move, indeed. However /usr/local/bin was in $PATH for the snap at the time we did craft that. It's not anymore.

**Comment by mardy** [comment]
I was trying a snap in xenial, and this would explain why it was not working. I guess we can close this, then (unless you prefer waiting until the fix actually gets published).

**Comment by didrocks** [comment]
Let's close it as you mentioned!

**Pull request closed without merging**
