### PR TITLE
Stage Fcitx frontend

### PR DESCRIPTION
**Pull request by brlin-tw**
This allows Fcitx input method framework to be used in Gtk3 snapped apps

Signed-off-by: 林博仁(Buo-ren Lin) <Buo.Ren.Lin@gmail.com>

### CODE REVIEW

**Comment by Lin-Buo-Ren** [comment]
> Have you tested that this is enough to make fcitx input work in gtk3 app snaps, or is this only a prerequisite?

I've copied the entire part definition with this addition to one of my snap, it works.

> And if this works we would probably want to add the corresponding packages to other desktop parts (fcitx-frontend-gtk2, fcitx-frontend-qt4, fcitx-frontend-qt5).

I agree.

**Comment by oSoMoN** [comment]
I finally got around to testing this, and I'm delighted to report that this works very nicely, no additional work needed. I successfully rebuilt the chromium snap with this additional stage package, and fcitx input (google-pinyin) just worked.

Note that snaps that connect to the gnome-3-26-1604 platform snap won't need this, for them fcitx input already works out of the box.

I also tested adding fcitx-frontend-qt5 to a qt5-based snap app (musescore), and this works well too.

**Comment by oSoMoN** [comment]
And as a follow-up I committed https://github.com/ubuntu/snapcraft-desktop-helpers/commit/a264e8f692624ec689887cda6358dd586ecf0e4a to add support for fcitx in qt5-based snaps.

**Comment by Lin-Buo-Ren** [comment]
> Could someone test with Sogou and report back. That should be a good proof.

What is Sogou exactly, I only heard of a Chinese company with the similar name.

**Comment by 8none1** [comment]
https://pinyin.sogou.com/linux/?r=pinyin

**Comment by oSoMoN** [comment]
> Could someone test with Sogou and report back. That should be a good proof.

I confirm this works in a bionic VM. I grabbed the 64bits deb from the sogou website, installed it and its dependencies, and successfully used it in various gnome app snaps that connect to the gnome-3-26-1604 platform snap.

**Pull request merged**
