### PR TITLE
Use also ubuntu-app-platform's lib/$ARCH dir for LD_LIBRARY_PATH (LP:…

### PR DESCRIPTION
**Pull request by tjyrinki**
… [#1642900](https://bugs.launchpad.net/ubuntu-app-platform/+bug/1642900))

### CODE REVIEW

**Comment by tjyrinki** [comment]
Asking oSoMoN to retest since he had the original bug (if he can back off his changes to workaround the bug). Looking at the desktop-helpers repository, I don't immediately see where the platform snap's $RUNTIME/lib/ would be added, only eg export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$RUNTIME/usr/lib/$ARCH

**Comment by tjyrinki** [comment]
Updated the pull request to reflect what might be needed.

**Comment by didrocks** [comment]
I don't think this fix is needed. I would just ask oSoMoN to rest trunk first (you don't have any ubuntu-app-platform/lib inclusion that's needed AFAIK).

**Comment by oSoMoN** [comment]
I can confirm that https://launchpad.net/bugs/1642900 is fixed without this change.

**Comment by didrocks** [comment]
Let's close that PR then.

**Pull request closed without merging**
